version: '2'

services:

  postgresql:
    restart: "$DOCKER_RESTART"
    build:
      context: ./services/postgres/
      args:
        POSTGRES_USER: "$POSTGRES_USER"
        POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
        POSTGRES_DB: "$POSTGRES_DB"
    ports:
      - "$POSTGRES_PUBLIC_PORT:5432"
    volumes:
      - ./runtime/postgresql/:/var/lib/postgresql/data/:rw
