CREATE DATABASE `<MYSQL_DATABASE>`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER '<MYSQL_USER>'@'%'
  IDENTIFIED BY '<MYSQL_USER_PASSWORD>';

GRANT ALL PRIVILEGES ON `<MYSQL_DATABASE>`.* TO '<MYSQL_USER>'@'%';

FLUSH PRIVILEGES;
